// This class was generated by 172 StubGenerator.
// Contents subject to change without notice.
// @generated

package main.java.com.owfg.facade.bb.StoreManagment.stub;

public interface StoreManagementImpl extends java.rmi.Remote {
	public main.java.com.owfg.facade.bb.StoreManagment.stub.Store[] getActiveStores() throws java.rmi.RemoteException;

	public main.java.com.owfg.facade.bb.StoreManagment.stub.Banner[] getBanners() throws java.rmi.RemoteException;

	public main.java.com.owfg.facade.bb.StoreManagment.stub.StoreManagementInfo getStoreManagementInfo(long storeId, java.lang.String upc) throws java.rmi.RemoteException;

}
