// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Reference Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package com.datacomm.weatherExample.stubs;


public class GetWeatherByZipCode {
    protected java.lang.String zipCode;
    
    public GetWeatherByZipCode() {
    }
    
    public GetWeatherByZipCode(java.lang.String zipCode) {
        this.zipCode = zipCode;
    }
    
    public java.lang.String getZipCode() {
        return zipCode;
    }
    
    public void setZipCode(java.lang.String zipCode) {
        this.zipCode = zipCode;
    }
}
