// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Reference Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package com.datacomm.weatherExample.stubs;


public class GetWeatherByZipCodeResponse {
    protected com.datacomm.weatherExample.stubs.WeatherForecasts getWeatherByZipCodeResult;
    
    public GetWeatherByZipCodeResponse() {
    }
    
    public GetWeatherByZipCodeResponse(com.datacomm.weatherExample.stubs.WeatherForecasts getWeatherByZipCodeResult) {
        this.getWeatherByZipCodeResult = getWeatherByZipCodeResult;
    }
    
    public com.datacomm.weatherExample.stubs.WeatherForecasts getGetWeatherByZipCodeResult() {
        return getWeatherByZipCodeResult;
    }
    
    public void setGetWeatherByZipCodeResult(com.datacomm.weatherExample.stubs.WeatherForecasts getWeatherByZipCodeResult) {
        this.getWeatherByZipCodeResult = getWeatherByZipCodeResult;
    }
}
