// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Reference Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package com.datacomm.weatherExample.stubs;


public class WeatherData {
    protected java.lang.String day;
    protected java.lang.String weatherImage;
    protected java.lang.String maxTemperatureF;
    protected java.lang.String minTemperatureF;
    protected java.lang.String maxTemperatureC;
    protected java.lang.String minTemperatureC;
    
    public WeatherData() {
    }
    
    public WeatherData(java.lang.String day, java.lang.String weatherImage, java.lang.String maxTemperatureF, java.lang.String minTemperatureF, java.lang.String maxTemperatureC, java.lang.String minTemperatureC) {
        this.day = day;
        this.weatherImage = weatherImage;
        this.maxTemperatureF = maxTemperatureF;
        this.minTemperatureF = minTemperatureF;
        this.maxTemperatureC = maxTemperatureC;
        this.minTemperatureC = minTemperatureC;
    }
    
    public java.lang.String getDay() {
        return day;
    }
    
    public void setDay(java.lang.String day) {
        this.day = day;
    }
    
    public java.lang.String getWeatherImage() {
        return weatherImage;
    }
    
    public void setWeatherImage(java.lang.String weatherImage) {
        this.weatherImage = weatherImage;
    }
    
    public java.lang.String getMaxTemperatureF() {
        return maxTemperatureF;
    }
    
    public void setMaxTemperatureF(java.lang.String maxTemperatureF) {
        this.maxTemperatureF = maxTemperatureF;
    }
    
    public java.lang.String getMinTemperatureF() {
        return minTemperatureF;
    }
    
    public void setMinTemperatureF(java.lang.String minTemperatureF) {
        this.minTemperatureF = minTemperatureF;
    }
    
    public java.lang.String getMaxTemperatureC() {
        return maxTemperatureC;
    }
    
    public void setMaxTemperatureC(java.lang.String maxTemperatureC) {
        this.maxTemperatureC = maxTemperatureC;
    }
    
    public java.lang.String getMinTemperatureC() {
        return minTemperatureC;
    }
    
    public void setMinTemperatureC(java.lang.String minTemperatureC) {
        this.minTemperatureC = minTemperatureC;
    }
}
