// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Reference Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package main.java.com.owfg.facade.bb.StoreManagement.stub;


public class GetActiveStoresResponse {
    protected main.java.com.owfg.facade.bb.StoreManagement.stub.Store[] _return;
    
    public GetActiveStoresResponse() {
    }
    
    public GetActiveStoresResponse(main.java.com.owfg.facade.bb.StoreManagement.stub.Store[] _return) {
        this._return = _return;
    }
    
    public main.java.com.owfg.facade.bb.StoreManagement.stub.Store[] get_return() {
        return _return;
    }
    
    public void set_return(main.java.com.owfg.facade.bb.StoreManagement.stub.Store[] _return) {
        this._return = _return;
    }
}
