// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Reference Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package main.java.com.owfg.facade.bb.StoreManagement.stub;


public class GetStoreManagementInfo {
    protected long arg0;
    protected java.lang.String arg1;
    
    public GetStoreManagementInfo() {
    }
    
    public GetStoreManagementInfo(long arg0, java.lang.String arg1) {
        this.arg0 = arg0;
        this.arg1 = arg1;
    }
    
    public long getArg0() {
        return arg0;
    }
    
    public void setArg0(long arg0) {
        this.arg0 = arg0;
    }
    
    public java.lang.String getArg1() {
        return arg1;
    }
    
    public void setArg1(java.lang.String arg1) {
        this.arg1 = arg1;
    }
}
