// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Reference Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package com.owfg.facade.bb.StoreManagement.stub;


public class GetWeatherByPlaceNameResponse {
    protected com.owfg.facade.bb.StoreManagement.stub.WeatherForecasts getWeatherByPlaceNameResult;
    
    public GetWeatherByPlaceNameResponse() {
    }
    
    public GetWeatherByPlaceNameResponse(com.owfg.facade.bb.StoreManagement.stub.WeatherForecasts getWeatherByPlaceNameResult) {
        this.getWeatherByPlaceNameResult = getWeatherByPlaceNameResult;
    }
    
    public com.owfg.facade.bb.StoreManagement.stub.WeatherForecasts getGetWeatherByPlaceNameResult() {
        return getWeatherByPlaceNameResult;
    }
    
    public void setGetWeatherByPlaceNameResult(com.owfg.facade.bb.StoreManagement.stub.WeatherForecasts getWeatherByPlaceNameResult) {
        this.getWeatherByPlaceNameResult = getWeatherByPlaceNameResult;
    }
}
