// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Reference Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package main.java.com.owfg.facade.bb.StoreManagement.stub;


public class GetWeatherByPlaceName {
    protected java.lang.String placeName;
    
    public GetWeatherByPlaceName() {
    }
    
    public GetWeatherByPlaceName(java.lang.String placeName) {
        this.placeName = placeName;
    }
    
    public java.lang.String getPlaceName() {
        return placeName;
    }
    
    public void setPlaceName(java.lang.String placeName) {
        this.placeName = placeName;
    }
}
