// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Reference Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package main.java.com.owfg.facade.bb.StoreManagement.stub;


public class StoreManagementInfo {
    protected double balanceOnHand;
    protected double forecast;
    protected double inTransit;
    protected java.lang.String itemDescription;
    protected long minimum;
    protected double onOrder;
    protected int pack;
    protected java.lang.String promotion;
    protected double regularPrice;
    protected java.lang.String source;
    protected long storeId;
    protected java.lang.String upc;
    
    public StoreManagementInfo() {
    }
    
    public StoreManagementInfo(double balanceOnHand, double forecast, double inTransit, java.lang.String itemDescription, long minimum, double onOrder, int pack, java.lang.String promotion, double regularPrice, java.lang.String source, long storeId, java.lang.String upc) {
        this.balanceOnHand = balanceOnHand;
        this.forecast = forecast;
        this.inTransit = inTransit;
        this.itemDescription = itemDescription;
        this.minimum = minimum;
        this.onOrder = onOrder;
        this.pack = pack;
        this.promotion = promotion;
        this.regularPrice = regularPrice;
        this.source = source;
        this.storeId = storeId;
        this.upc = upc;
    }
    
    public double getBalanceOnHand() {
        return balanceOnHand;
    }
    
    public void setBalanceOnHand(double balanceOnHand) {
        this.balanceOnHand = balanceOnHand;
    }
    
    public double getForecast() {
        return forecast;
    }
    
    public void setForecast(double forecast) {
        this.forecast = forecast;
    }
    
    public double getInTransit() {
        return inTransit;
    }
    
    public void setInTransit(double inTransit) {
        this.inTransit = inTransit;
    }
    
    public java.lang.String getItemDescription() {
        return itemDescription;
    }
    
    public void setItemDescription(java.lang.String itemDescription) {
        this.itemDescription = itemDescription;
    }
    
    public long getMinimum() {
        return minimum;
    }
    
    public void setMinimum(long minimum) {
        this.minimum = minimum;
    }
    
    public double getOnOrder() {
        return onOrder;
    }
    
    public void setOnOrder(double onOrder) {
        this.onOrder = onOrder;
    }
    
    public int getPack() {
        return pack;
    }
    
    public void setPack(int pack) {
        this.pack = pack;
    }
    
    public java.lang.String getPromotion() {
        return promotion;
    }
    
    public void setPromotion(java.lang.String promotion) {
        this.promotion = promotion;
    }
    
    public double getRegularPrice() {
        return regularPrice;
    }
    
    public void setRegularPrice(double regularPrice) {
        this.regularPrice = regularPrice;
    }
    
    public java.lang.String getSource() {
        return source;
    }
    
    public void setSource(java.lang.String source) {
        this.source = source;
    }
    
    public long getStoreId() {
        return storeId;
    }
    
    public void setStoreId(long storeId) {
        this.storeId = storeId;
    }
    
    public java.lang.String getUpc() {
        return upc;
    }
    
    public void setUpc(java.lang.String upc) {
        this.upc = upc;
    }
}
