// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Reference Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package com.datacomm.weatherExample.stubs;


public class ArrayOfWeatherData {
    protected com.datacomm.weatherExample.stubs.WeatherData[] weatherData;
    
    public ArrayOfWeatherData() {
    }
    
    public ArrayOfWeatherData(com.datacomm.weatherExample.stubs.WeatherData[] weatherData) {
        this.weatherData = weatherData;
    }
    
    public com.datacomm.weatherExample.stubs.WeatherData[] getWeatherData() {
        return weatherData;
    }
    
    public void setWeatherData(com.datacomm.weatherExample.stubs.WeatherData[] weatherData) {
        this.weatherData = weatherData;
    }
}
