// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Reference Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package com.datacomm.weatherExample.stubs;


public class GetWeatherByPlaceNameResponse {
    protected com.datacomm.weatherExample.stubs.WeatherForecasts getWeatherByPlaceNameResult;
    
    public GetWeatherByPlaceNameResponse() {
    }
    
    public GetWeatherByPlaceNameResponse(com.datacomm.weatherExample.stubs.WeatherForecasts getWeatherByPlaceNameResult) {
        this.getWeatherByPlaceNameResult = getWeatherByPlaceNameResult;
    }
    
    public com.datacomm.weatherExample.stubs.WeatherForecasts getGetWeatherByPlaceNameResult() {
        return getWeatherByPlaceNameResult;
    }
    
    public void setGetWeatherByPlaceNameResult(com.datacomm.weatherExample.stubs.WeatherForecasts getWeatherByPlaceNameResult) {
        this.getWeatherByPlaceNameResult = getWeatherByPlaceNameResult;
    }
}
