// This class was generated by 172 StubGenerator.
// Contents subject to change without notice.
// @generated

package com.datacomm.weatherExample.stubs;

public interface WeatherForecastSoap extends java.rmi.Remote {
	public com.datacomm.weatherExample.stubs.WeatherForecasts getWeatherByZipCode(java.lang.String zipCode) throws java.rmi.RemoteException;

	public com.datacomm.weatherExample.stubs.WeatherForecasts getWeatherByPlaceName(java.lang.String placeName) throws java.rmi.RemoteException;

}
